### ISSUE TITLE
forgot to run storage:link when install

### ISSUE THREAD

**Issue by mix5003** [JeffreyWay/council#121]
currently it can not change avatar.

I think when run council:install it should call storage:link too.
but that storage:link command isn't work on windows.
so i don't know how to deal with it

**Comment by fhugas** [comment]
Best way to deal with it is not to use Windows for developing :nerd_face:  , second best way is to use something like vagrant and ssh into that to create storage link. Or maybe dual-boot is the second best option, this is what I use since I found vagrant a bit confusing and odd to work with. Can't remember what it was, but think it too was related with the linking of files/folders, been a while since i tried it out now.
