### ISSUE TITLE
Api Resources

### ISSUE THREAD

**Issue by fbcarpinato** [JeffreyWay/council#156]
In all of the api calls that we have in the project we are just fetching data from the database and returning it as json, this can lead to several issues when we want to update the schema because they are strictly related right now.

For example, imagine that we want to change the thread field "body" into "text" in the database, this will eventually break every client that uses the api to fetch threads.

One solution to this problem is to implement Eloquent API Resources.

**Comment by Indemnity83** [comment]
Or explicitly define the toArray() method in each model, backed with a unit test.

**Comment by lgalaz** [comment]
I think Api Resources may not be required here just yet since this is not intended as a public Api and therefore it might be overkill to make that stretch, maybe @Indemnity83 suggestion makes more sense although that to could be a bit of a stretch at this moment too? 

What are your thoughts on that?
At what point do you think it's necessary to verify you comply to an interface on your Api endpoints?

**Comment by davorminchorov** [comment]
I don't see a point of using resources unless the forum is transformed into a full API with Vue as a SPA.

**Comment by fbcarpinato** [comment]
I agree with you, i opened the issue as a reminder for the future

**Comment by JeffreyWay** [comment]
Yeah, as the others noted, it's not much of an issue at the moment. There is only one consumer of the API, so if we do change the field from "body" to "text," we'll just update the client to match. No biggie.
