### ISSUE TITLE
Feature: add "reputation" support.

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/council#20]
It would be nice if users accrue "reputation" points as they participate in the forum. 

1. Create a thread: 10 points
2. Leave a reply: 2 points
3. Reply is marked as "best reply" - 50 points
4. Reply was liked: 4 points

**Comment by highsolutions** [comment]
Nice feature!

**Comment by highsolutions** [comment]
This one will be interesting:
5. Thread appeared in search (e.g. 1 point)

Gathering which results (in this case - threads) are showed from Algolia is tricky and it'll be great to see how you handle this.

**Comment by gileswells** [comment]
6. Thread marked as spam: -15 points (original points + penalty)
7. Reply maked as spam: -3 points

I mean yes it seems like reputation would be as valuable as reddit karma or points from Who's Line but if there's gamification sadly people will attempt to game it.

**Comment by JeffreyWay** [comment]
If it's marked as spam, we'd delete their account entirely.

**Comment by MattMangoni** [comment]
Is this already fully implemented?

**Comment by JeffreyWay** [comment]
Only about half has. I’ll finish it up soon.

**Comment by Tray2** [comment]
I think a level should be displayed instead of the number of experience.
Let's say a user like @JeffreyWay has been replying to all the threads he would soon get like 999999999XP and it would keep on incrementing until it won't fit in an integer anymore.

So something like:

- Tiny Grasshopper
- Grasshopper
- Budgie
- Eagle
- Emu
- Gnu

Then on the profile page you'll see how many xp you got and how far it is to the next level.

**Comment by MattMangoni** [comment]
@JeffreyWay I've been experimenting with the reputation system in the last couple of hours, before going to work. I won't submit a PR for this since I guess you want to finish the work yourself, but I can't wait to see how you will deal (if you're going to) with points subtraction on best answer change, deletion and so on :)

Just for reference, here's the branch I was working on:
https://github.com/MattMangoni/council/tree/advanced_reputation

**Comment by devmsh** [comment]
I currently develop a project I working on, and I feel more  comfortable with the following api

```php
$user->award($points)
```

To prevent growing the `User` class, and to add the ability to award multiple entities like `User` or `Group` in a game, I added an `award` method using `Awardable` trait rather that `Reputation` class.

```php
trait Awardable
{
    const THREAD_WAS_PUBLISHED = 10;
    const REPLY_POSTED = 2;
    const BEST_REPLY_AWARDED = 50;

    /**
     * Award reputation points.
     *
     * $param integer $points
     */
    public function award($points)
    {
        $this->increment('reputation', $points);
    }
}
```

I also feel that points history with clear message is a MUST so we can recalc the user points any time.

I know that it's not a reputation system series, but I'm really interested to hear from you :)

**Comment by MattMangoni** [comment]
@devmsh Well, you have to consider that if you have a dedicated table for points, App\Reputation can easily be transformed into a model.

That's exactly what I did in my fork, pointing it to a "reputation_points" table.
But tbh, I like the idea of awarding the user directly better.

Another thing I did was adding a new row to the table for each interaction.
Instead of deleting points, I basically "give" -X points on reply thread/deletion and best reply change (ONLY if the new best reply belongs to a different user then the previous one). Not sure how much that will impact on performance for large scale applications.

Then, I set a custom attribute called "reputation" to the User model in order for it to be accessible the same way as before.

**Comment by JeffreyWay** [comment]
Yeah I do like `$user->award()` too. I specifically chose a dedicated `Reputation` class for the reason that @MattMangoni mentioned. We'll at some point switch to a dedicated table for storing reputation.
