### ISSUE TITLE
.dev domain issue in chrome

### ISSUE THREAD

**Issue by MordiSacks** [JeffreyWay/council#4]
Hi,
I know you usually use foo.dev for a local development project
Unfortunately chrome forces all .dev to redirect to https, As I understand the gTLD .dev is registered by google  and for some reason they have codded this into chrome.
If you don't have https setup for your local development, you cannot use .dev

**Comment by Chinese1904** [comment]
What's the issue here? He explained it in his series.

**Comment by svenluijten** [comment]
Indeed! [`.dev` was registered by Google back in 2014](https://icannwiki.org/.dev), and they recently added it to the HSTS preload list which will eventually be adopted by all major browsers. 

Luckily for us, the folks over at IETF thought to reserve a handful of TLDs (`.test`, `.example`, `.invalid`, `.localhost`) that cannot ever be registered by anyone, just for local development and testing. You can read more about that [here](https://iyware.com/dont-use-dev-for-development/#reservedtopleveldomainnames).

Personally, I've switched to using `.test`, because it's nice and short (better than `.localhost` 😛) and it won't ever be reserved and preloaded. Hope this helps, @MordiSacks! 🙂

**Comment by MordiSacks** [comment]
@Chinese1904 the issue is that council.dev should be to council.???
@svenluijten Thank's I have seen `.test` etc. suggested, But i was hesitant because I thought 

> well sooner or later someone is going to register that as well

Thank's for mentioning the fact that they are reserved!

**Comment by Chinese1904** [comment]
I don't think it's an issue, rather a personal preference.

I generally develop using the .dev TLD, and now that Chrome "forces" certificates on those, it seems rather like a good behavior for us to enable them on local development as well

**Comment by MordiSacks** [comment]
@Chinese1904 
I disagree for 2 reasons
1. since .dev is infact a viable  gTLD, we might actually collide with an actual domain.
2. I cannot see any benefit using SSL on a local development environment (form a web developer point of view).

**Comment by Chinese1904** [comment]
Sure, I guess we have to agree to disagree.

1. It's been known for years that .dev is available as a TLD. Hence, it's always been a personal preference for people to use this for their development domains.
2. insecure content errors are quiet common issues

**Comment by exwizzard** [comment]
@Chinese1904 If you check the [googles registry page](https://www.registry.google/) you can see that they plan to launch .dev in the first half of 2018 which means someone could buy council.dev on day one and make it unusable for everyone else.

**Comment by shiroamada** [comment]
@svenluijten `.localhost` will be an issue if your web server running via docker / VM. Chrome reference it as 127.0.0.1, so you can't resolve your server.

I switch from `.localhost` to `.test` to avoid this issue. `.test` will have more control on it.

**Comment by MordiSacks** [comment]
@Chinese1904 I guess I would agree with you that in some cases ssl will be useful, but defiantly not for your average  project, but on the other hand, what if you wanted to test non SSL specifics, like displaying a flash message 

> Beware your connection is unsecure
How would you test that if chrome forces you to SSL?
