### ISSUE TITLE
Reverse instead of Reduce

### ISSUE THREAD

**Issue by shaqaruden** [JeffreyWay/council#59]
In Lesson 8 Jeffrey uses the term reduce a user deletes a thread or a reply to lower the users reputation.

I would refer to these as transactions. Thus when a user deleted a thread or reply we should  'reverse' the reputation transaction related to the thread or reply

**Comment by Chinese1904** [comment]
"reverse" is more like inverse of "award", that's why I think it would be a more appropriate use for this specific scenario as well

```php
public static function reduce($user, $points)
{
    $user->decrement('reputation', $points);
}
```

However, if we ever want to, for some reason in the future, reduce the reputation for whatever reason that's not directly related to the "awarding", it would be more appropriate if it was left named "reduce". It's more broad. Not sure though, which scenario this would happen haha

Anyways, I don't mind it being named "reduce", because it leaves it more open for future additions, but I guess it could always be renamed as well

**Comment by eoghanobrien** [comment]
How about forfeit? https://www.wordhippo.com/what-is/the-opposite-of/award.html

**Comment by JeffreyWay** [comment]
@eoghanobrien I originally used `forfeit` in that video, but then I changed it. It made me think that you're forfeiting all of your reputation, and you're not. 

Not sure about `reverse`. I think there's still a better term.

**Comment by JeffreyWay** [comment]
Maybe `award` is wrong too. Maybe your reputation `grow`s. 

```php
Reputation::grow();
```

And then reverse would be... 

https://www.powerthesaurus.org/grow/antonyms

Detract? Shrink?

**Comment by MattMangoni** [comment]
@JeffreyWay @eoghanobrien I usually try to keep it as simple as possibile in these situations.
I'd probably end up with just Reputation::add() and Reputation::subtract()

Or maybe addPoints() and subtractPoints(), just to be a little more specific.

**Comment by Lirianer** [comment]
Maybe `gain()` and `lose()`?

```
Reputation::gain(10);

Reputation::lose(5);
```

**Comment by eoghanobrien** [comment]
@JeffreyWay I think you're right, changing `award` is probably a better approach but then why not simply `increase` and `decrease`. It's little less exciting perhaps.

**Comment by MattMangoni** [comment]
@Lirianer that's definitely the best option I've heard.

**Comment by JeffreyWay** [comment]
Okay, we'll go with `grow` and `lose` for now.
