### ISSUE TITLE
Theme Proposal

### ISSUE THREAD

**Issue by roberthamel** [JeffreyWay/council#61]
I've done a few projects recently and utilized [Vuetify](https://vuetifyjs.com/). It's quite flexible and looks nice too. I would like to open a pull request to begin incorporating that theme into this project if others also agree this would be a good approach to take.

**Comment by zaknes** [comment]
Er.. maybe Tailwind? I can only predict that he'll also do a course on it.

**Comment by MattMangoni** [comment]
Yes, I vote for tailwind.
Maybe we also think about a simile template system too.

But yeah, @JeffreyWay will probably make some videos about that.

**Comment by shaqaruden** [comment]
I vote for vuetify.

**Comment by roberthamel** [comment]
I do like Vuetify a lot but I suspect that Tailwind would be the more popular choice given it's connection to the Laravel community and it's innovative flexibility. Tailwind is a great choice and also has my vote.

I posed this question mainly because resources are not always there to tackle something like this. If there are plans to create, say, a Tailwind tutorial series, this project would be a perfect use case for that. However, since it's possible to have the visual theme of the project be a community effort, I wanted to find out which direction is going to be the preferred path.

I would like to help contribute to this, but not if the effort will not be considered. 

Also, because there are a million different ways to theme the application, a simple pull request doesn't seem like the right approach. Creating a separate feature branch seems more practical, if this is going to be a community effort.

Thoughts?

**Comment by Diddyy** [comment]
Perhaps further down the line Council could have a theme system.
This system would allow users to switch between styles so they have customisation of the forum they use. This way we could have multiple themes which individuals could contribute to created a more personalised forum.

However this would need to be discussed on the best way to implement and perhaps would be better added after some more basic functions are added?

Just though I'd throw the idea out now while we're talking about themes instead of making a new issue. This approach would then allow you to have your style of vuetify as well as a classic tailwind design.

**Comment by yanitor** [comment]
+1 for tailwind

The problem what i see with this themes idea is you need to write for any theme new vue components. Or is there a way i dont know.

**Comment by JeffreyWay** [comment]
We'll likely use Tailwind. The design is almost ready, so we'll tackle this soon.
